"""create users table

Revision ID: 22b59affa90c
Revises: ad728a014374
Create Date: 2026-01-15 11:03:23.963874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22b59affa90c'
down_revision = 'ad728a014374'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
