"""create policies and claims tables

Revision ID: 326a65bd6a8d
Revises: 22b59affa90c
Create Date: 2026-01-15 11:19:55.817041

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '326a65bd6a8d'
down_revision = '22b59affa90c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('policy_number', sa.String(), nullable=False),
    sa.Column('policy_type', sa.String(), nullable=False),
    sa.Column('insurer_name', sa.String(), nullable=False),
    sa.Column('sum_insured', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('premium_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('coverage_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_policies_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policies'))
    )
    op.create_index(op.f('ix_policies_policy_number'), 'policies', ['policy_number'], unique=True)
    op.create_table('claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_number', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('claim_type', sa.String(), nullable=False),
    sa.Column('incident_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('incident_location', sa.String(), nullable=True),
    sa.Column('incident_description', sa.Text(), nullable=True),
    sa.Column('claimed_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('approved_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('readiness_score', sa.Integer(), nullable=True),
    sa.Column('fraud_score', sa.Integer(), nullable=True),
    sa.Column('decision_type', sa.String(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], name=op.f('fk_claims_policy_id_policies')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_claims_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claims'))
    )
    op.create_index(op.f('ix_claims_claim_number'), 'claims', ['claim_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claims_claim_number'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_policies_policy_number'), table_name='policies')
    op.drop_table('policies')
    # ### end Alembic commands ###
