"""add policies and claims

Revision ID: 6bcd2fec02d0
Revises: 326a65bd6a8d
Create Date: 2026-01-15 11:25:30.384594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bcd2fec02d0'
down_revision = '326a65bd6a8d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
