"""add documents and timeline

Revision ID: d12da06cf9f2
Revises: 43b9a62045ae
Create Date: 2026-01-15 11:33:00.033877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd12da06cf9f2'
down_revision = '43b9a62045ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
